### PR TITLE
Jk comments to dom

### PR DESCRIPTION
**Pull request by josephkane**
added setTimeout function to the enemy attack, to provide time for the player comments to display. Not sure if this is the best way to do it. Probably will have a merge conflict with my previous pull request. Also, I don't ultimately intend on displaying the comments where they are now, I just wanted to see what yall thought of doing it this way.

### CODE REVIEW

**Comment by aoswalt** [comment]
Hmm. It feels fragile, but I can't think of a better way off the top of my head unless you can tie it into the animation timing somehow. Overall, I would like to add a return to the fight/attack methods that says what happened so it could be output as well as trigger animations, but we will see.

**Comment by aoswalt** [comment]
:+1:

**Comment by josephkane** [comment]
@aoswalt Totally hear that. On my machine at least, it seems like the animations wait on the setTimeout function to complete before it runs. I'll leave this pull request open and we can discuss tomorrow.

**Comment by aoswalt** [comment]
Unless plans changed, I don't think we will have time tomorrow. Scott was talking about starting presentations at 9. I say, if it works, ship it and come back to it if the opportunity arises.

**Pull request merged**
